Repository adrianmaciuc/break-it-playwright-javascript-project, pull requests merged in 2023-11, with the labels that each got.

#46 update README.md contributor name
  README.md
Labels: bug

#69 config updates
  playwright.config.js
Labels: Task

#74 Add test for page title
  tests/iulianExample.spec.js
Labels: Difficulty Beginner

#73 Check header redirects
  tests/homePage/header-part-1.spec.js
Labels: Difficulty Beginner
